version: '3'
services:
   test:
      build: .
      ports:
         - "127.0.0.1::8888"
         - "127.0.0.1::8787"
         - "127.0.0.1::8501"
      volumes:
         - ./:/mnt
      entrypoint: bash
      stdin_open: true
      tty: true
      environment:
        - PYTHONPATH=/mnt

